# Site settings
title: Zoe Cai
email: hello@zoecai.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineering student at the University of Auckland. I write well-structured and maintainable code. This is my blog, powered by Jekyll and hosted on Github pages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zoecai.com" # the base hostname & protocol for your site
twitter_username: zoercai
github_username:  zoercai
analytics :
  provider : google
  google : 
      tracking_id : 'UA-56081917-1'

# Build settings
markdown: kramdown
collections:
 projects:
  output: true
