# Site settings
title: Zoe Cai
email: hello@zoecai.com
description: > # this means to ignore newlines until "baseurl:"
  Blog and portfolio of Zoe Cai, a software engineering student at the University of Auckland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zoecai.com" # the base hostname & protocol for your site
twitter_username: zoercai
github_username:  zoercai

# Build settings
markdown: kramdown
